### ISSUE TITLE
Remove gray markers from the map

### ISSUE THREAD

**Issue by mushon** [davidhalfon/worldRadioProject#2]
this is a small yet crucial fix that would extend the map's look dramatically

**Comment by davidhalfon** [comment]
what grey markers? I've just opened the map on three different web browser and no grey markers were shown.

**Comment by mushon** [comment]
These gray markers appear in every browser I checked:
Are we talking about this map? Are you sure it holds the most up-to-date code?
http://www.david-halfon.com/worldRadio/

![4up4khk](https://cloud.githubusercontent.com/assets/27123/8589878/b7756e52-2623-11e5-99a6-6d0132dbe4f9.png)

**Comment by mushon** [comment]
![4up4khk](https://cloud.githubusercontent.com/assets/27123/8589878/b7756e52-2623-11e5-99a6-6d0132dbe4f9.png)

**Comment by davidhalfon** [comment]
That's strange.. maybe you should try delete caching? 
We're talking about web right? not mobile
and here it is on Chrome, Safari and Firefox:

![2015 07 09 10 26 07](https://cloud.githubusercontent.com/assets/9497100/8590023/fde9e8c6-2624-11e5-9084-5faaa6a767bb.png)
![2015 07 09 10 25 17](https://cloud.githubusercontent.com/assets/9497100/8590022/fde8a61e-2624-11e5-9e9c-5ae208692df2.png)
![2015 07 09 10 24 53](https://cloud.githubusercontent.com/assets/9497100/8590024/fdee9a88-2624-11e5-94cc-61bee2175722.png)

**Comment by mushon** [comment]
Very vey weird. I’ve cleaned my cache but I’m still seeing them on every browser on my computer but I checked on another computer and didn’t see it there…

-- 
Mushon Zer-Aviv
Mushon.com | Shual.com | @mushon

On July 9, 2015 at 10:27:54 AM, davidhalfon (notifications@github.com) wrote:

http://www.david-halfon.com/worldRadio/

**Comment by davidhalfon** [comment]
Nor in every other computer I checked.

**Comment by mushon** [comment]
weird… closing.
